name: build-pipeline

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/workflows/**'
      - '.nx'
      - '.vscode'
      - '.verdaccio'
      - 'README.md'

jobs:
  build-validate:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    # env:
    #   NPM_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
    #   NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
    #   NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
    #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.x.x
          cache: npm

      - name: install dependencies
        run: npm ci

      - name: check for lint errors
        run: npm run lint

      - name: build application
        run: npm run build

      - name: test application
        run: npm run test

      # - name: Configure npm
      #   run: |
      #     echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
      #     cat .npmrc
      #   env:
      #     NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Publish components (Github packages)
      #   run: |
      #     for LIBRARY in $(yarn nx affected:libs --base=$last_version --head=$current_version --plain | awk 'NR > 2 && $1 != "Done" { print $1 }')
      #     do
      #       cd ./dist/libs/$LIBRARY
      #       npm publish --registry https://npm.pkg.github.com --no-git-tag-version --no-push --yes
      #       cd ..
      #       cd ..
      #     done
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: check affected applications
        run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: commit after the release
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[skip ci] updating release packages'

